weather_forcast:
  outputs:
    dev:
      dbname: airflow
      host: postgres
      password: 'airflow'
      port: 5432
      schema: ods
      threads: 1
      type: postgres
      user: airflow
  target: dev
